:root{
  --bg:#f6f8fb;
  --panel:#ffffff;
  --text:#172033;
  --muted:#667085;
  --line:#d8dee8;
  --blue:#1d4ed8;
  --blue-2:#e8f0ff;
  --green:#07855f;
  --amber:#b45309;
  --red:#b42318;
  --shadow:0 8px 20px rgba(15,23,42,.08);
  --radius:14px;
  --mid-atlantic:#e0f2fe;
  --northeast:#ede9fe;
  --southeast:#dcfce7;
  --west:#ffedd5;
}
*{box-sizing:border-box}
body{margin:0;background:var(--bg);color:var(--text);font-family:Inter,Segoe UI,Arial,sans-serif;font-size:13px;line-height:1.35}
a{color:var(--blue);text-decoration:none} a:hover{text-decoration:underline}
.topbar{display:flex;justify-content:space-between;gap:20px;align-items:center;padding:20px 24px;background:linear-gradient(135deg,#0f172a,#1e3a8a);color:#fff;box-shadow:var(--shadow)}
.eyebrow{text-transform:uppercase;letter-spacing:.12em;font-size:11px;margin:0 0 4px;color:#bfdbfe}.topbar h1{margin:0;font-size:24px}.subtitle{margin:6px 0 0;color:#dbeafe;max-width:850px}.top-actions{display:flex;gap:8px;flex-wrap:wrap;justify-content:flex-end}
main{padding:16px 20px 32px}.btn,button{border:1px solid var(--line);background:#fff;color:var(--text);border-radius:10px;padding:8px 11px;font-weight:700;cursor:pointer;font-size:12px}.btn:hover,button:hover{border-color:#94a3b8}.btn.primary{background:#2563eb;border-color:#2563eb;color:#fff}.btn.small{padding:6px 9px}.status-panel,.source-upload-panel,.filters,.viewbar,.metrics,.active-filters{max-width:1600px;margin:0 auto 12px}.status-panel{display:flex;gap:12px;align-items:center;background:var(--panel);border:1px solid var(--line);border-left:5px solid var(--blue);border-radius:var(--radius);padding:12px 14px;box-shadow:var(--shadow)}.status-panel p{margin:2px 0 0;color:var(--muted)}.loader-dot{width:11px;height:11px;border-radius:50%;background:#94a3b8}.status-panel.loading .loader-dot{background:#2563eb;animation:pulse 1s infinite}@keyframes pulse{50%{opacity:.35}}
.source-upload-panel{background:#fff;border:1px solid var(--line);border-radius:var(--radius);padding:10px 14px}.source-upload-panel summary{font-weight:800;cursor:pointer}.upload-grid{display:grid;grid-template-columns:repeat(4,minmax(180px,1fr));gap:10px;margin-top:10px}.upload-grid label{display:flex;flex-direction:column;gap:5px;font-weight:700}.hint{color:var(--muted);font-size:12px;margin:8px 0 0}
.metrics{display:grid;grid-template-columns:repeat(6,minmax(140px,1fr));gap:10px}.metric{background:#fff;border:1px solid var(--line);border-radius:var(--radius);padding:11px 12px;box-shadow:var(--shadow)}.metric span{display:block;color:var(--muted);font-size:11px;text-transform:uppercase;letter-spacing:.05em}.metric strong{font-size:20px}
.filters{display:grid;grid-template-columns:2fr repeat(8, minmax(120px, 1fr));gap:10px;background:#fff;border:1px solid var(--line);border-radius:var(--radius);padding:12px;box-shadow:var(--shadow)}.field{display:flex;flex-direction:column;gap:5px}.field label{font-weight:800;font-size:11px;color:#334155;text-transform:uppercase;letter-spacing:.04em}.field input,.field select{width:100%;border:1px solid var(--line);border-radius:9px;padding:8px;background:#fff;color:var(--text);font-size:12px}.field select[multiple]{min-height:108px;padding:5px}.ruca-field{position:relative}.label-with-help{display:flex!important;align-items:center;gap:6px}.help-icon{position:relative;display:inline-flex;align-items:center;justify-content:center;width:16px;height:16px;border-radius:999px;background:#e0f2fe;color:#075985;font-size:11px;font-weight:900;text-transform:none;letter-spacing:0;cursor:help}.tooltip-card{display:none;position:absolute;z-index:20;left:0;top:22px;width:310px;background:#0f172a;color:#fff;border-radius:12px;padding:10px 12px;box-shadow:0 12px 32px rgba(15,23,42,.28);font-size:12px;line-height:1.35;font-weight:500;text-transform:none;letter-spacing:0}.tooltip-card strong{display:block;color:#bfdbfe;margin-bottom:4px}.help-icon:hover .tooltip-card,.help-icon:focus .tooltip-card{display:block}.field-hint{font-size:11px;color:var(--muted);margin-top:-1px}.mini-clear{padding:4px 7px;border-radius:8px;font-size:11px;align-self:flex-start;background:#f8fafc}.field.wide{min-width:240px}.field.tiny{max-width:80px}.viewbar{display:flex;justify-content:space-between;align-items:center}.segmented{display:inline-flex;border:1px solid var(--line);background:#fff;border-radius:999px;overflow:hidden}.segmented button{border:0;border-radius:0;background:transparent}.segmented button.active{background:#0f172a;color:#fff}.pagination-controls{display:flex;align-items:center;gap:8px;color:var(--muted)}.pagination-controls select{border:1px solid var(--line);border-radius:8px;padding:5px}
.active-filters{color:#475569}.chip{display:inline-flex;align-items:center;gap:4px;border-radius:999px;padding:3px 8px;font-weight:800;font-size:11px;border:1px solid transparent;white-space:nowrap}.chip.region-Mid-Atlantic{background:var(--mid-atlantic)}.chip.region-Northeast{background:var(--northeast)}.chip.region-Southeast{background:var(--southeast)}.chip.region-West{background:var(--west)}.chip.rural{background:#dcfce7;color:#166534}.chip.not-rural{background:#fee2e2;color:#991b1b}.chip.unknown{background:#f1f5f9;color:#475569}.chip.status{background:#e0f2fe;color:#075985}.chip.warn{background:#fef3c7;color:#92400e}
.table-wrap{max-width:1600px;margin:0 auto;background:#fff;border:1px solid var(--line);border-radius:var(--radius);box-shadow:var(--shadow);overflow:auto}table{width:100%;border-collapse:collapse;min-width:1120px}th,td{border-bottom:1px solid #e5e7eb;padding:7px 8px;text-align:left;vertical-align:top}th{position:sticky;top:0;background:#f8fafc;font-size:11px;text-transform:uppercase;letter-spacing:.05em;color:#334155;z-index:1;cursor:pointer}td{font-size:12px}.name-cell strong{display:block}.subtext{color:var(--muted);font-size:11px}.website-link{display:inline-block;max-width:130px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.contact-stack span{display:block}.table-actions button{padding:5px 7px;border-radius:8px}.hidden{display:none!important}
.card-grid{max-width:1600px;margin:0 auto;display:grid;grid-template-columns:repeat(auto-fill,minmax(310px,1fr));gap:12px}.prospect-card{background:#fff;border:1px solid var(--line);border-radius:var(--radius);box-shadow:var(--shadow);padding:13px}.prospect-card h3{margin:6px 0;font-size:15px}.card-meta{display:flex;flex-wrap:wrap;gap:5px;margin-bottom:8px}.card-row{display:flex;justify-content:space-between;gap:12px;border-top:1px solid #eef2f7;padding:7px 0}.card-row span:first-child{font-weight:800;color:#475569}.card-actions{display:flex;gap:8px;margin-top:10px}
dialog{border:0;border-radius:18px;padding:0;width:min(860px,96vw);box-shadow:0 30px 80px rgba(15,23,42,.35)}dialog::backdrop{background:rgba(15,23,42,.45)}.dialog-card{position:relative;padding:20px;background:#fff}.dialog-close{position:absolute;top:10px;right:12px;border:0;background:#f1f5f9;border-radius:999px;width:32px;height:32px;font-size:20px}.detail-head{padding-right:36px}.detail-head h2{margin:0 0 4px}.detail-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:12px}.detail-box{border:1px solid var(--line);border-radius:var(--radius);padding:12px;background:#fbfdff}.detail-box h3{margin:0 0 8px;font-size:13px;text-transform:uppercase;letter-spacing:.05em;color:#334155}.detail-form{display:grid;grid-template-columns:1fr 1fr;gap:10px}.detail-form label{display:flex;flex-direction:column;gap:4px;font-weight:800;color:#334155}.detail-form input,.detail-form select,.detail-form textarea{border:1px solid var(--line);border-radius:9px;padding:8px;font:inherit}.detail-form textarea{grid-column:1/-1;min-height:88px}.source-list{display:grid;grid-template-columns:1fr 1fr;gap:12px}.source-list article{border:1px solid var(--line);border-radius:var(--radius);padding:12px;background:#fbfdff}.source-list h3{margin:0 0 6px}.source-list a{display:inline-block;margin-right:12px;font-weight:800}
.print-title{display:none}
@media (max-width:1100px){.topbar{flex-direction:column;align-items:flex-start}.filters{grid-template-columns:1fr 1fr}.metrics{grid-template-columns:repeat(2,1fr)}.upload-grid{grid-template-columns:1fr 1fr}.detail-grid,.source-list{grid-template-columns:1fr}}
@media print{body{background:#fff;font-size:10px}.topbar{background:#fff;color:#000;box-shadow:none;border-bottom:2px solid #111;padding:10px}.subtitle,.eyebrow,.top-actions,.no-print,.source-upload-panel,.filters,.viewbar,.dialog-close{display:none!important}main{padding:6px}.status-panel{border:0;box-shadow:none;padding:0}.metrics{grid-template-columns:repeat(4,1fr);gap:5px}.metric{box-shadow:none;padding:6px}.table-wrap{box-shadow:none;border:0}.table-wrap table{min-width:0}th,td{padding:4px}.no-print{display:none!important}.card-grid{grid-template-columns:1fr 1fr;gap:6px}.prospect-card{box-shadow:none;break-inside:avoid}.print-title{display:block}}
